/* The following code was generated by JFlex 1.6.1 */

import java.util.Map;
import java.util.TreeMap;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>LexicalAnalyzer.jflex</tt>
 */
class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int PROGRAM = 2;
  public static final int COMMENT = 4;
  public static final int PRECOMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  3,  4,  4,  5, 5
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\4\1\6\1\6\1\3\22\0\1\5\1\17\6\0"+
    "\1\37\1\40\1\7\1\42\1\35\1\41\1\33\1\43\12\2\3\0"+
    "\1\36\3\0\1\15\1\1\1\10\1\22\1\20\1\26\1\14\1\27"+
    "\1\24\2\1\1\30\1\16\1\21\1\13\1\11\1\34\1\12\1\32"+
    "\1\25\6\1\6\0\1\15\1\1\1\10\1\22\1\20\1\26\1\14"+
    "\1\27\1\24\2\1\1\30\1\16\1\21\1\13\1\11\1\34\1\12"+
    "\1\32\1\25\6\1\12\0\1\6\252\0\2\23\115\0\1\31\u1ea8\0"+
    "\1\6\1\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\2\3\1\2\2\4\1\5\1\6"+
    "\1\7\1\3\1\10\1\11\2\6\1\12\2\6\1\5"+
    "\2\6\1\5\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\1\3\22\1\3\1\23\1\3\1\24\1\2"+
    "\4\6\1\25\1\0\1\26\1\6\1\26\1\6\10\0"+
    "\1\2\1\0\2\6\1\27\1\0\1\6\1\0\2\6"+
    "\11\0\1\2\1\0\3\6\1\0\1\6\2\30\1\0"+
    "\1\6\1\31\1\32\1\33\1\34\1\35\1\36\1\0"+
    "\1\37\1\40\1\41\1\2\1\0\1\6\1\42\1\43"+
    "\2\44\1\0\1\6\1\45\1\2\1\46\1\0\1\6"+
    "\1\47\2\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\330\0\u0144\0\330\0\374\0\330\0\u0168\0\u018c"+
    "\0\u01b0\0\330\0\330\0\u01d4\0\u01f8\0\330\0\u021c\0\u0240"+
    "\0\u0264\0\u0288\0\u02ac\0\u02d0\0\330\0\330\0\330\0\330"+
    "\0\330\0\330\0\330\0\u02f4\0\330\0\u0168\0\u0240\0\u0318"+
    "\0\330\0\u033c\0\330\0\u0360\0\u0384\0\u03a8\0\u03cc\0\u03f0"+
    "\0\u0168\0\u0414\0\330\0\u0438\0\u0168\0\u045c\0\u0480\0\u04a4"+
    "\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0120\0\u02f4\0\u0558\0\u057c"+
    "\0\u05a0\0\u05c4\0\u05e8\0\u060c\0\u0630\0\u0654\0\u0678\0\u069c"+
    "\0\u06c0\0\u06e4\0\u0708\0\u072c\0\u0750\0\u0774\0\u0798\0\u07bc"+
    "\0\u07e0\0\u0804\0\u0828\0\u084c\0\u0870\0\u0894\0\u08b8\0\u08dc"+
    "\0\330\0\u0168\0\u0900\0\u0924\0\u0168\0\330\0\330\0\330"+
    "\0\330\0\330\0\u0948\0\330\0\330\0\330\0\u096c\0\u0990"+
    "\0\u09b4\0\330\0\u0168\0\330\0\u0168\0\u09d8\0\u09fc\0\330"+
    "\0\u0a20\0\330\0\u0a44\0\u0a68\0\374\0\330\0\u0168";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\1\7\1\11\2\7\1\12\1\7\1\10"+
    "\1\13\5\10\1\7\3\10\1\7\5\10\1\7\1\10"+
    "\1\7\1\10\10\7\1\10\1\7\1\11\2\7\1\12"+
    "\1\14\1\15\1\13\5\10\1\14\2\10\1\15\1\7"+
    "\5\10\1\7\1\10\1\7\1\10\7\7\1\16\1\17"+
    "\1\20\1\21\1\22\1\7\1\12\1\23\1\17\1\24"+
    "\1\25\4\17\1\26\1\27\1\17\1\30\1\31\1\32"+
    "\1\33\3\17\1\16\1\17\1\34\1\17\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\16\1\17\1\20"+
    "\1\11\1\7\1\44\1\12\1\45\1\46\1\24\1\25"+
    "\4\17\1\45\1\27\1\17\1\47\1\31\1\32\1\33"+
    "\3\17\1\16\1\17\1\34\1\17\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\3\7\1\50\1\51\1\7"+
    "\1\12\40\7\1\52\1\53\1\7\1\12\35\7\45\0"+
    "\2\10\5\0\7\10\1\0\3\10\1\0\5\10\1\0"+
    "\1\10\1\0\1\10\13\0\1\7\40\0\2\10\5\0"+
    "\2\10\1\54\4\10\1\0\3\10\1\0\5\10\1\0"+
    "\1\10\1\0\1\10\10\0\2\17\5\0\7\17\1\0"+
    "\3\17\1\0\5\17\1\0\1\17\1\0\1\17\11\0"+
    "\1\20\45\0\1\22\40\0\2\17\5\0\2\17\1\55"+
    "\4\17\1\0\3\17\1\0\5\17\1\0\1\17\1\0"+
    "\1\17\10\0\2\17\5\0\7\17\1\0\1\56\2\17"+
    "\1\0\5\17\1\0\1\17\1\0\1\17\10\0\2\17"+
    "\5\0\7\17\1\0\1\17\1\57\1\17\1\0\4\17"+
    "\1\60\1\0\1\17\1\0\1\17\10\0\2\17\5\0"+
    "\3\17\1\61\3\17\1\0\3\17\1\0\5\17\1\0"+
    "\1\17\1\0\1\17\30\0\1\62\4\0\1\63\16\0"+
    "\2\17\5\0\7\17\1\0\1\17\1\64\1\17\1\0"+
    "\2\17\1\65\2\17\1\0\1\17\1\0\1\17\10\0"+
    "\2\17\5\0\7\17\1\0\3\17\1\0\3\17\1\66"+
    "\1\17\1\0\1\17\1\0\1\17\22\0\1\67\1\70"+
    "\1\71\2\0\1\72\1\73\6\0\1\74\16\0\1\75"+
    "\1\7\1\76\42\0\1\51\43\0\1\53\40\0\2\10"+
    "\5\0\3\10\1\77\3\10\1\0\3\10\1\0\5\10"+
    "\1\0\1\10\1\0\1\10\10\0\2\17\5\0\7\17"+
    "\1\0\3\17\1\100\1\101\4\17\1\0\1\17\1\0"+
    "\1\17\10\0\2\17\5\0\5\17\1\102\1\17\1\0"+
    "\3\17\1\0\5\17\1\0\1\17\1\0\1\17\10\0"+
    "\2\17\5\0\7\17\1\0\2\17\1\103\1\0\5\17"+
    "\1\0\1\17\1\0\1\17\10\0\2\17\5\0\7\17"+
    "\1\0\3\17\1\0\5\17\1\104\1\105\1\0\1\17"+
    "\34\0\1\106\17\0\2\17\5\0\7\17\1\0\3\17"+
    "\1\0\1\17\1\107\3\17\1\0\1\17\1\0\1\17"+
    "\10\0\2\17\5\0\7\17\1\0\1\110\2\17\1\0"+
    "\5\17\1\0\1\17\1\0\1\17\21\0\1\111\51\0"+
    "\1\112\4\0\1\113\37\0\1\114\56\0\1\115\22\0"+
    "\1\116\4\0\1\117\43\0\1\120\4\0\1\121\17\0"+
    "\2\10\5\0\4\10\1\122\2\10\1\0\3\10\1\0"+
    "\5\10\1\0\1\10\1\0\1\10\30\0\1\123\23\0"+
    "\2\17\5\0\7\17\1\0\1\17\1\124\1\17\1\0"+
    "\5\17\1\0\1\17\1\0\1\17\10\0\2\17\5\0"+
    "\7\17\1\0\2\17\1\125\1\0\5\17\1\0\1\17"+
    "\1\0\1\17\10\0\2\17\5\0\7\17\1\0\2\17"+
    "\1\126\1\127\1\130\4\17\1\0\1\17\1\0\1\17"+
    "\27\0\1\131\24\0\2\17\5\0\7\17\1\0\1\132"+
    "\2\17\1\0\5\17\1\0\1\17\1\0\1\17\27\0"+
    "\1\133\24\0\2\17\5\0\7\17\1\0\1\134\2\17"+
    "\1\0\5\17\1\0\1\17\1\0\1\17\10\0\2\17"+
    "\5\0\7\17\1\0\1\17\1\135\1\17\1\0\5\17"+
    "\1\0\1\17\1\0\1\17\42\0\1\136\43\0\1\137"+
    "\43\0\1\140\43\0\1\141\43\0\1\142\35\0\1\143"+
    "\51\0\1\144\43\0\1\145\43\0\1\146\11\0\2\10"+
    "\5\0\2\10\1\147\4\10\1\0\3\10\1\0\5\10"+
    "\1\0\1\10\1\0\1\10\34\0\1\150\17\0\2\17"+
    "\5\0\7\17\1\0\3\17\1\0\1\17\1\151\3\17"+
    "\1\0\1\17\1\0\1\17\10\0\2\17\4\0\1\152"+
    "\7\17\1\0\3\17\1\0\5\17\1\0\1\17\1\0"+
    "\1\17\10\0\2\17\5\0\3\17\1\153\3\17\1\0"+
    "\3\17\1\0\5\17\1\0\1\17\1\0\1\17\35\0"+
    "\1\154\16\0\2\17\5\0\7\17\1\0\3\17\1\0"+
    "\2\17\1\155\2\17\1\0\1\17\1\0\1\17\23\0"+
    "\1\156\30\0\2\17\5\0\4\17\1\157\2\17\1\0"+
    "\3\17\1\0\5\17\1\0\1\17\1\0\1\17\42\0"+
    "\1\160\11\0\2\10\5\0\5\10\1\161\1\10\1\0"+
    "\3\10\1\0\5\10\1\0\1\10\1\0\1\10\16\0"+
    "\1\162\35\0\2\17\4\0\1\162\7\17\1\0\3\17"+
    "\1\0\5\17\1\0\1\17\1\0\1\17\27\0\1\163"+
    "\24\0\2\17\5\0\7\17\1\0\1\164\2\17\1\0"+
    "\5\17\1\0\1\17\1\0\1\17\10\0\2\10\5\0"+
    "\6\10\1\165\1\0\3\10\1\0\5\10\1\0\1\10"+
    "\1\0\1\10\21\0\1\166\32\0\2\17\5\0\2\17"+
    "\1\167\4\17\1\0\3\17\1\0\5\17\1\0\1\17"+
    "\1\0\1\17\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2700];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\2\1\1\11\1\1\1\11\1\1\1\11"+
    "\3\1\2\11\2\1\1\11\6\1\7\11\1\1\1\11"+
    "\3\1\1\11\1\1\1\11\6\1\1\0\1\11\3\1"+
    "\10\0\1\1\1\0\3\1\1\0\1\1\1\0\2\1"+
    "\11\0\1\1\1\0\3\1\1\0\1\1\1\11\1\1"+
    "\1\0\2\1\5\11\1\0\3\11\1\1\1\0\1\1"+
    "\1\11\1\1\1\11\1\1\1\0\1\1\1\11\1\1"+
    "\1\11\1\0\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
private TreeMap<String, Integer> identifiers = new TreeMap<String, Integer>();

/**
* Add an identifier and it's declaration location to the list of identifiers
*/
private void addIdentifier(){
  if (!identifiers.containsKey(yytext())) {
    identifiers.put(yytext(), yyline+1);
  }
}

/**
* Helper function too create new symbol with position
* @param type of LexicalUnit inferred
* @return created symbol
*/
private Symbol symbolBuilder(LexicalUnit unit){
    return new Symbol(unit, yyline, yycolumn, yytext());
}

/**
* Helper function too create new symbol with position
* @param type of LexicalUnit inferred
* @param value associated
* @return created symbol
*/
private Symbol symbolBuilder(LexicalUnit unit, Object value){
    return new Symbol(unit, yyline, yycolumn, value);
}

private void log(Symbol s){
  System.out.println("line: "+ (yyline+1) + " " + s);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
      System.out.println("Identifiers");
  for (Map.Entry<String, Integer> i: identifiers.entrySet()){
    System.out.println(i.getKey() + " " + i.getValue());
  }

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 41: break;
          case 2: 
            { log(symbolBuilder(LexicalUnit.VARNAME)); yybegin(PROGRAM);
            }
          case 42: break;
          case 3: 
            { System.out.print(yytext());
            }
          case 43: break;
          case 4: 
            { yybegin(PRECOMMENT);
            }
          case 44: break;
          case 5: 
            { System.out.println("TOKEN NOT RECOGNIZED: " + yytext());
            }
          case 45: break;
          case 6: 
            { addIdentifier(); log(symbolBuilder(LexicalUnit.VARNAME));
            }
          case 46: break;
          case 7: 
            { log(symbolBuilder(LexicalUnit.NUMBER, new Integer(yytext())));
            }
          case 47: break;
          case 8: 
            { log(symbolBuilder(LexicalUnit.ENDLINE, " "));
            }
          case 48: break;
          case 9: 
            { log(symbolBuilder(LexicalUnit.TIMES));
            }
          case 49: break;
          case 10: 
            { log(symbolBuilder(LexicalUnit.ENDLINE, " ")); yybegin(COMMENT);
            }
          case 50: break;
          case 11: 
            { log(symbolBuilder(LexicalUnit.COMMA));
            }
          case 51: break;
          case 12: 
            { log(symbolBuilder(LexicalUnit.EQUAL));
            }
          case 52: break;
          case 13: 
            { log(symbolBuilder(LexicalUnit.LEFT_PARENTHESIS));
            }
          case 53: break;
          case 14: 
            { log(symbolBuilder(LexicalUnit.RIGHT_PARENTHESIS));
            }
          case 54: break;
          case 15: 
            { log(symbolBuilder(LexicalUnit.MINUS));
            }
          case 55: break;
          case 16: 
            { log(symbolBuilder(LexicalUnit.PLUS));
            }
          case 56: break;
          case 17: 
            { log(symbolBuilder(LexicalUnit.DIVIDE));
            }
          case 57: break;
          case 18: 
            { yybegin(COMMENT);
            }
          case 58: break;
          case 19: 
            { yybegin(PROGRAM);
            }
          case 59: break;
          case 20: 
            { yybegin(YYINITIAL);
            }
          case 60: break;
          case 21: 
            { log(symbolBuilder(LexicalUnit.DO));
            }
          case 61: break;
          case 22: 
            { log(symbolBuilder(LexicalUnit.IF));
            }
          case 62: break;
          case 23: 
            { log(symbolBuilder(LexicalUnit.END)); yybegin(YYINITIAL);
            }
          case 63: break;
          case 24: 
            { log(symbolBuilder(LexicalUnit.ELSE));
            }
          case 64: break;
          case 25: 
            { log(symbolBuilder(LexicalUnit.THEN));
            }
          case 65: break;
          case 26: 
            { log(symbolBuilder(LexicalUnit.OR));
            }
          case 66: break;
          case 27: 
            { log(symbolBuilder(LexicalUnit.GREATER_EQUAL));
            }
          case 67: break;
          case 28: 
            { log(symbolBuilder(LexicalUnit.GREATER));
            }
          case 68: break;
          case 29: 
            { log(symbolBuilder(LexicalUnit.AND));
            }
          case 69: break;
          case 30: 
            { log(symbolBuilder(LexicalUnit.EQUAL_COMPARE));
            }
          case 70: break;
          case 31: 
            { log(symbolBuilder(LexicalUnit.DIFFERENT));
            }
          case 71: break;
          case 32: 
            { log(symbolBuilder(LexicalUnit.SMALLER_EQUAL));
            }
          case 72: break;
          case 33: 
            { log(symbolBuilder(LexicalUnit.SMALLER));
            }
          case 73: break;
          case 34: 
            { log(symbolBuilder(LexicalUnit.READ));
            }
          case 74: break;
          case 35: 
            { log(symbolBuilder(LexicalUnit.ENDDO));
            }
          case 75: break;
          case 36: 
            { log(symbolBuilder(LexicalUnit.ENDIF));
            }
          case 76: break;
          case 37: 
            { log(symbolBuilder(LexicalUnit.NOT));
            }
          case 77: break;
          case 38: 
            { log(symbolBuilder(LexicalUnit.PRINT));
            }
          case 78: break;
          case 39: 
            { log(symbolBuilder(LexicalUnit.PROGRAM));
            }
          case 79: break;
          case 40: 
            { log(symbolBuilder(LexicalUnit.INTEGER));
            }
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexicalAnalyzer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        LexicalAnalyzer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new LexicalAnalyzer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
